### ISSUE TITLE
Introduce map support (without a backing message type) in protoc-gen-openapi

### ISSUE THREAD

**Issue by hkf57** [google/gnostic#228]
Currently, if the following protobuf is run through the openAPI generator:

```
... snip ...
message Foo {
  // Sample
  map<string, string> bar = 1
}
```
The following result is produced:
```
bar:
  type: array
  items:
    $ref: '#/components/schemas/BarEntry'
    description: Sample
```

Which will require the following addition to ensure that this works:

```
... snip ...
message BarEntry {
  string key = 1
  string value = 2
}
```

I propose changes that will result in the below openAPI v3 spec, without the addition of `BarEntry`:
```
bar:
  type: object
  additionalProperties:
    type: string
    description: Sample
```
