### ISSUE TITLE
invalid generated swagger from proto with protoc-gen-openapi

### ISSUE THREAD

**Issue by vtolstov** [google/gnostic#311]
i have proto file with 
{ post: "/some/path/XXX?RqUID={RqUID}&RqTm={RqTm}"; body: "*"; };
so i think that generated swagger have RqUID and RqTm in path query parameters and other in body
but
```
paths:
    /some/path/XXX?RqUID={RqTm: // this is invalid
        post:
            tags:
                - XXX
            operationId: someOperation
            parameters:
                - name: RqUID
                  in: path
                  required: true
                  schema:
                    type: string
                - name: RqTm
                  in: path
                  required: true
                  schema:
                    type: string
```
