### ISSUE TITLE
proto-gen-openapi: a question about using "openapiv3/annotations.proto" to generate yaml

### ISSUE THREAD

**Issue by yzhaoyu** [google/gnostic#346]
proto-gen-openapi: gnostic provides **openapiv3/annotations.proto**, so I'm using it in my proto file, want to generate some openapiv3 descriptions, but when i use protoc instruction, the generated yaml file doesn't contain **openapi.v3.document** info.
Therefore I test the example file [message.proto](https://github.com/google/gnostic/blob/main/cmd/protoc-gen-openapi/examples/tests/openapiv3annotations/message.proto#L25), it also doesn't work. How can I from such code:
```proto
option (openapi.v3.document) = {
  info: {
    title: "Title from annotation";
    version: "Version from annotation";
    description: "Description from annotation";
    contact: {
      name: "Contact Name";
      url: "https://github.com/google/gnostic";
      email: "gnostic@google.com";
    }
    license: {
      name: "Apache License";
      url: "https://github.com/google/gnostic/blob/master/LICENSE";
    }
  }
  components: {
    security_schemes: {
      additional_properties: [
        {
          name: "BasicAuth";
          value: {
            security_scheme: {
              type: "http";
              scheme: "basic";
            }
          }
        }
      ]
    }
  }
};
```
to generate this:
```yaml
info:
    title: Title from annotation
    description: Description from annotation
    contact:
        name: Contact Name
        url: https://github.com/google/gnostic
        email: gnostic@google.com
    license:
        name: Apache License
        url: https://github.com/google/gnostic/blob/master/LICENSE
    version: Version from annotation
```
