### ISSUE TITLE
openapiv3 tags

### ISSUE THREAD

**Issue by 1226151667** [google/gnostic#363]
After setting the tag, why not overwrite the original default but recreate the tag，
proto file:
```protobuf		
service Test {
	rpc CreateTest (CreateTestRequest) returns (CreateTestReply) {
		option (google.api.http) = {
			post: "/api/test",
			body: "*"
		};
		option (openapi.v3.operation) = {
			tags: ["TS1"],
		};
	}
}
```
yaml file:
```yaml
paths:
    /api/test:
        post:
            tags:
                - Test
                - TS1
         ..................
```
How do I do it, please, Thanks!
