### ISSUE TITLE
Create a Buf plugin for `protoc-gen-openapi`

### ISSUE THREAD

**Issue by hbjydev** [google/gnostic#365]
It would be really nice to have a remote plugin uploaded to Buf's BSR for `protoc-gen-openapi`, so that we can build our OpenAPI 3 schemas from our protobuf schemas using Buf in smaller Docker containers.

The `buf.gen.yaml` would essentially look like this:

```yml
---
version: v1
plugins:
  - remote: buf.build/protocolbuffers/plugins/go:v1.28.1-1
    out: gen/go
    opt:
      - paths=source_relative

  # ...

  - remote: buf.build/gnostic/plugins/protoc-gen-openapi:<version>-<release>
    out: gen/oapi3
    opt:
      - title=OpenAPI v3
```

Then, we can just run `buf generate` to spit out all of this stuff from a pretty tiny Docker build step.

```dockerfile
FROM bufbuild/buf:1.7.0 AS buf

WORKDIR /src

COPY buf.yaml buf.yaml
COPY buf.gen.yaml buf.gen.yaml
COPY proto/ proto/

RUN buf generate
```

Like this one.

I'd love to be able to get this one built, it would be a really big help to people like me who are trying to stick to Buf for all their protobuf needs, and using remote plugins reduces the number of required tools to install locally versus using `protoc` locally, and having to install all the relevant `protoc` extensions with it.

Thanks! :)

**Comment by rauanmayemir** [comment]
I think this is related to #337.

From what I've gathered looking into the code structure and issues, the main obstacle to moving forward with adopting buf is that large clients like kubectl directly depend on this repository and protobuf structure.

I found gnostic's protoc-gen-openapi more natural for gRPC-first stack than the grpc-gateway's plugin.
Gently pinging @timburks to ask about the next steps or priorities.

Maybe we need to wait for the unbundling of gnostic first before this plugin could be updated. But if IUUC, making protoc-gen-openapi use different protobuf schemas wouldn't break much because openapi annotation schemas are only needed for `protoc-gen-openapi`, not the gnostic itself (i.e the part that converts protobuf _from_ openapi).

**Comment by hbjydev** [comment]
> I think this is related to #337.
> 
> From what I've gathered looking into the code structure and issues, the main obstacle to moving forward with adopting buf is that large clients like kubectl directly depend on this repository and protobuf structure.

Hi there,

So it's not really related to #337, this isn't trying to make gnostic or protoc-gen-openapi use Buf for its dependencies or anything.

Basically, Buf has a concept of "remote plugins". They essentially let people who don't want to download the binaries for each protoc plugin use them directly through buf's Schema Registry. They are only there to make it possible to use `protoc-gen-openapi` work as a Buf plugin.

Hope that clarifies a little bit, but I'm happy to give it another go if not, haha.

**Comment by timburks** [comment]
@rauanmayemir That's right - we set up github.com/google/gnostic-models to provide some isolation. I think that has been around long enough now that we can start restructuring and other improvements to work well with Buf.

**Comment by conbon** [comment]
Any further thoughts or movement on this?

**Comment by timburks** [comment]
Reading up, it looks like this is about pointing `buf` to a locally-installed version of `protoc-gen-openapi`. Has someone already done this? If something needs to be uploaded to the gnostic org, I'll do that, but I'm not clear on what that is (yet).

**Comment by timburks** [comment]
... or do we need a PR on https://github.com/bufbuild/plugins ?

**Comment by mfridman** [comment]
Hey @timburks 👋 , I can probably help with that (I help maintain [bufbuild/plugins](https://github.com/bufbuild/plugins)).

This particular plugin has come up a lot recently, and if you'd like, we can publish it as a Remote Plugin to https://buf.build/plugins. 

This enables folks to reference the plugin without having to download it locally. Let me know and I can follow up on this.

**Comment by mfridman** [comment]
There's a few new commits, but the latest tag is `v0.6.9`. What do you think of bumping the tag?

**Comment by alanrichman** [comment]
This feels like it is most of the way there: https://github.com/bufbuild/plugins/tree/main/plugins/community/google-gnostic-openapi

But has anyone had any luck including `openapi.v3.operations` and similar options in their proto built with Buf? https://github.com/google/gnostic/tree/main/openapiv3

**Comment by rauanmayemir** [comment]
@alanrichman gnostic's `protoc-get-openapi` _mostly_ works for me as a plugin with buf. What problem are you experiencing?

```yaml
# buf.yaml
# ...
deps:
- buf.build/gnostic/gnostic
- buf.build/googleapis/googleapis
```

```yaml
# buf.gen.yaml
# ...
version: v2
managed:
  enabled: true
  override:
  - file_option: go_package_prefix
    value: go.example.com/gen/proto
plugins:
- remote: buf.build/community/google-gnostic-openapi:v0.7.0
  out: ../schema/gen/path
  opt:
  - naming=proto
  - fq_schema_naming=true
  - enum_type=string
  include_imports: true
  include_wkt: true
# ...
```

And service definition:
```proto
syntax = "proto3";

package acme.package.v1;

import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";

service MyResourceService {
  rpc CreateResource(CreateResourceRequest) returns (CreateResourceResponse) {
    option (google.api.http) = {
      post: "/v1/resources"
      body: "*"
    };

    option (gnostic.openapi.v3.operation) = {
      security: {
        additional_properties: {
          name: "ApiKeyAuth"
          value: {value: ""}
        }
      }
    };
  }
}


message CreateResourceRequest {
  option (gnostic.openapi.v3.schema) = {
    required: ["id"]
  };

  // Id of the resource
  int32 id = 1 [
    (gnostic.openapi.v3.property) = {
      example: {yaml: "712345"}
    }
  ];
}
```

**Comment by alanrichman** [comment]
I was not finding this link in the BSR (buf.build/gnostic/gnostic) and it got me unstuck, thank you!

**Comment by alanrichman** [comment]
Something else I am encountering with this Buf plugin, if I run it as you have using a `remote` line everything works as expected:

```yaml
  - remote: buf.build/community/google-gnostic-openapi
    out: gen/openapiv3
    opt:
      - naming=proto
      - fq_schema_naming=true
```

With all of the same options but switching to a Go Tool install for this command I see some odd behavior

```yaml
  - local: ["go", "tool", "protoc-gen-openapi"]
    out: gen/openapiv3
    opt:
      - naming=proto
      - fq_schema_naming=true
```

It produces this warning one fewer times than the number of proto files I have, and the output in `openapi.yaml` will contain only one of the proto file's content.

```
duplicate generated file name "openapi.yaml". Generation will continue without error here and drop the second occurrence of this file, but please raise an issue with the maintainer of the plugin.
```

It is in my `tool` block in `go.mod` like this:

```go
tool (
        ...
	github.com/google/gnostic/cmd/protoc-gen-openapi
)
```

Thanks!

**Comment by rauanmayemir** [comment]
Yeah I also had something like that, likely because go tool requires specified protos to be unique.

**Comment by alanrichman** [comment]
Figured it out! Needed `strategy: all`

```yaml
- local: ["go", "tool", "protoc-gen-openapi"]
    out: gen/openapiv3
    strategy: all
```
