### ISSUE TITLE
When the field type is a, it is invalid when setting the minimum to 0

### ISSUE THREAD

**Issue by shuqingzai** [google/gnostic#373]
### proro
```proto
    uint32 mediNum = 2 [
      (validate.rules).uint32 = {gte: 0, lte: 16777215},

      (openapi.v3.property) = {
        title: "number";
        description: "number";
        type: "integer";
        minimum: 0;
        maximum: 16777215;
      }
    ];
```

### yaml
```yaml
    mediNum:
        title: number
        maximum: 1.6777215e+07
        type: integer
        description: number
        format: uint32
```
