### ISSUE TITLE
[protoc-gen-openapi] how can i generate required query parama?

### ISSUE THREAD

**Issue by code-tbd** [google/gnostic#379]
[protoc-gen-openapi](https://github.com/google/gnostic/tree/main/cmd/protoc-gen-openapi)

I generate `openapi.yaml` by this cmd tool, but my annotation `[(google.api.field_behavior) = REQUIRED]` not take effect. 
It take effect in body params, but not query.

I get the result:
``` yaml
- name: username                
  in: query       
  schema:                      
    type: integer              
    format: int32              
```

I expect it generate like this:
``` yaml
- name: username                
  in: query
  required: true                  
  schema:                      
    type: integer              
    format: int32              
```
