### ISSUE TITLE
protoc-gen-openapi: Enum types that use stringified boolean values like `"TRUE"` are treated as the real boolean values

### ISSUE THREAD

**Issue by zaakn** [google/gnostic#407]
## env
- protoc-gen-openapi: v0.6.8
- protoc flags: `--openapi_opt naming=proto,enum_type=string`

## proto file

```protobuf
enum Trinary {
	NULL = 0;
	TRUE = 1;
	FALSE = 2;
}

message Condition {
	Trinary attached = 1;
}
```

## expected output

```yaml
Condition:
    type: object
    properties:
        attached:
            enum:
                - 'NULL'
                - 'TRUE'
                - 'FALSE'
            type: string
            format: enum
```

## actual output

```yaml
Condition:
    type: object
    properties:
        attached:
            enum:
                - NULL
                - TRUE
                - FALSE
            type: string
            format: enum
```

-----
I know it's better not to use reserved words, so this is just for usage feedback.
